apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gk8s-db
  labels:
    db: 5gk8s-mysql
spec:
  capacity:
    storage: 10Gi
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: normal
  nfs:
    path: /nfs/data/5gk8s/db/mysql
    server: 192.168.2.43
