apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-5gk8s-db
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: normal
  selector:
    matchLabels:
      db: 5gk8s-mysql
