apiVersion: v1
kind: Service
metadata:
  name: sv-flask-app
  # labels:
  #   name: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    name: flask-app