apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gk8s-db
  labels:
    db: mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: normal
  nfs:
    path: /nfs/data/5gk8s/db/mysql
    server: 192.168.56.21
