apiVersion: v1
kind: Service
metadata:
  name: svc-mysqldb-5gk8s
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31306
  selector:
    db: 5gk8s-db
